routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//route landing page
Route::get('/', 'LandingPageController@welcome');
Route::get('place/view/{id}', 'LandingPageController@placeview');
Route::get('/about', function () {
    return view('about');
});

//route verifikasi user
Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//route front search
Route::get('search-destination', ['as'=>'search-destination','uses'=>'AllSearchController@destination']);
Route::get('search-budget', ['as'=>'search-budget','uses'=>'AllSearchController@budget']);
Route::get('search-car', ['as'=>'search-car','uses'=>'AllSearchController@car']);

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
  Route::resource('cartypes', 'CarTypesController');
  Route::resource('cars', 'CarsController');
  Route::resource('categories', 'CategoriesController');
  Route::resource('places', 'PlacesController');
  Route::resource('transactions', 'TransactionsController');
  Route::resource('confirmations', 'ConfirmationsController');
  Route::resource('members', 'MembersDataController');
  /*
   * route myprofil dan ubah *admin*
   */
  Route::get('settings', 'SettingsController@profile');
  Route::post('settings', 'SettingsController@update');
  Route::get('settings/password', 'SettingsController@editPassword');
  Route::post('settings/password', 'SettingsController@updatePassword');
  /*
   *  export laporan
   */
  Route::get('export/transactions', [
    'as' => 'export.transactions',
    'uses' => 'TransactionsController@export'
  ]);
  Route::post('export/transactions', [
    'as' => 'export.transactions.post',
    'uses' => 'TransactionsController@exportPost'
  ]);

});

Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function () {
  Route::resource('orders', 'MemberOrdersController');
  Route::get('orders/confirmation/{id}', 'MemberOrdersController@conf');
  Route::post('orders/confirmation/{id}', 'MemberOrdersController@storeconf');
  Route::get('orders/dest/{id}', 'MemberOrdersController@orderdest');
  Route::get('orders/car/{id}', 'MemberOrdersController@ordercar');
  Route::get('orders/cetak/{id}', 'MemberOrdersController@cetak');
  /*
  --route myprofil dan ubah password *member*
  */
  Route::get('settings', 'MemberSettingsController@profile');
  Route::post('settings', 'MemberSettingsController@update');
  Route::get('settings/password', 'MemberSettingsController@editPassword');
  Route::post('settings/password', 'MemberSettingsController@updatePassword');
});


/*
-- route ajax dropdown wilayah
*/
Route::get('/admin/places/kabupaten/{id}', 'PlacesController@kabupaten');
Route::get('/admin/places/kecamatan/{id}', 'PlacesController@kecamatan');
Route::get('/admin/places/kelurahan/{id}', 'PlacesController@kelurahan');

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Session;
use DB;
use App\Transaction;
use Yajra\Datatables\Datatables;
use Yajra\Datatables\Html\Builder;
use Auth;
use Excel;

class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index(Request $request, Builder $htmlBuilder)
       {
         if ($request->ajax()) {
           $data = Transaction::with('user','place','car','admin')->get();
           return Datatables::of($data)
             ->addColumn('action', function($transaction){
               return view('datatable._action_transaction', [
                 'model' => $transaction,
                 'form_url' => route('transactions.destroy', $transaction->id),
                 'edit_url' => route('transactions.edit', $transaction->id),
                 'conf_url' => route('transactions.show', $transaction->id),
                 'confirm_message' => 'Yakin mau menghapus transaksi ' . $transaction->code . '?'
               ]);
             })->make(true);
           }

           $html = $htmlBuilder
             ->addColumn(['data' => 'code', 'name'=>'code', 'title'=>'Kode Transaksi'])
             ->addColumn(['data' => 'user.name', 'name'=>'user.name', 'title'=>'Nama Pelanggan'])
             ->addColumn(['data' => 'place.name', 'name'=>'place.name', 'title'=>'Tujuan'])
             ->addColumn(['data' => 'car.name', 'name'=>'car.name', 'title'=>'Merk mobil'])
             ->addColumn(['data' => 'total_participants', 'name'=>'total_participants', 'title'=>'Jumlah orang'])
             ->addColumn(['data' => 'start_date', 'name'=>'start_date', 'title'=>'Tanggal Pergi'])
             ->addColumn(['data' => 'end_date', 'name'=>'end_date', 'title'=>'Tanggal Kembali'])
             ->addColumn(['data' => 'total_cost', 'name'=>'total_cost', 'title'=>'Total Harga'])
             ->addColumn(['data' => 'admin.name', 'name'=>'admin.name', 'title'=>'Admin'])
             ->addColumn(['data' => 'status', 'name'=>'status', 'title'=>'Status'])
             ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

             return view('transactions.index')->with(compact('html'));
       }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::with('user','place','car')->find($id);
        $confirmation = DB::table('confirmations')
        ->where('transaction_id','=', $id)->get();
        return view('transactions.confirmation')->with(compact('transaction','confirmation'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $transaction = Transaction::find($id);
      return view('transactions.edit')->with(compact('transaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'user_id' => 'required',
        'place_id' => 'required',
        'car_id' => 'required',
        'total_participants' => 'required|numeric',
        'total_cost' => 'required|numeric',
        'status' => 'required'
      ]);

      $transaction = Transaction::find($id);
      $transaction->update($request->all());

      Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Transaksi Berhasil Diubah"
      ]);

    return redirect()->route('transactions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $transaction = Transaction::find($id);

      // hapus image lama, jika ada
      if ($transaction->confirmation->image) {
        $old_image = $transaction->confirmation->image;
        $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
        . DIRECTORY_SEPARATOR . $transaction->confirmation->image;
        try {
          File::delete($filepath);
        } catch (FileNotFoundException $e) {
          // File sudah dihapus/tidak ada
        }
      }
      $transaction->delete();

      Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Data Berhasil dihapus"
      ]);

      return redirect()->route('transactions.index');
    }

    public function export()
    {
      return view('transactions.export');
    }

    public function exportPost(Request $request)
    {
      // validasi
      $this->validate($request, [
        'month'=>'required',
      ], [
        'month.required'=>'Anda belum memilih bulan. Pilih bulan terlebih dahulu!'
      ]);

      $transactions = Transaction::with('user','place','car','admin')
                      ->whereMonth('created_at', $request->get('month'))
                      ->orderBy('status', 'asc')
                      ->get();

      Excel::create('Laporan Transaksi Bulanan bdgtranservice', function($excel) use ($transactions) {

        // Set property
        $excel->setTitle('Laporan Transaksi Bulanan bdgtranservice')
        ->setCreator(Auth::user()->name);
        $excel->sheet('Laporan Transaksi', function($sheet) use ($transactions) {
          $row = 1;
          $sheet->row($row, [
            'Kode Transaksi',
            'Nama Pelanggan',
            'Tujuan',
            'Merk Mobil',
            'Jumlah Orang',
            'Tangga Pergi',
            'Tanggal Kembali',
            'Total Harga',
            'Admin',
            'Status'
          ]);
          foreach ($transactions as $transaction) {
            $sheet->row(++$row, [
              $transaction->code,
              $transaction->user->name,
              $transaction->place->name,
              $transaction->car->name,
              $transaction->total_participants,
              $transaction->start_date,
              $transaction->end_date,
              $transaction->total_cost,
              $transaction->admin->name,
              $transaction->status
            ]);
          }
        });
      })->export('xls');
    }
}

resources/views/transactions/_conf.blade.php
<!-- transaksi_id hidden -->
{!! Form::hidden('transaction_id', $transaction->id, ['class'=>'form-control','readonly']) !!}

<div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
  <label class="col-md-3 control-label">Kode Transaksi</label>
  <div class="col-md-9">
    <input type="text" class="form-control" value="{{$transaction->code}}" readonly>
    {!! $errors->first('code', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('payment_method') ? 'has-error' : '' !!}">
  {!! Form::label('name', 'Metode Pembayaran', ['class'=>'col-md-3 control-label']) !!}
  <div class="col-md-9">
    {!! Form::select('payment_method',[
      'Transfer'=>'Transfer',
      'Cash'=>'Cash'
    ],$transaction->confirmation->payment_method,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Metode Pembayaran']) !!}
    {!! $errors->first('payment_method', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('info') ? 'has-error' : '' !!}">
  {!! Form::label('name', 'Keterangan', ['class'=>'col-md-3 control-label']) !!}
  <div class="col-md-9">
    {!! Form::select('info',[
      'BCA'=>'BCA',
      'Mandiri'=>'Mandiri',
      'BNI'=>'BNI',
      'BRI'=>'BRI',
      'Cash' =>'Cash',
    ],$transaction->confirmation->info,[
      'class'=>'form-control',
      'placeholder' => 'Keterangan Pembayaran']) !!}
    {!! $errors->first('info', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('paid_total') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Total dibayar', ['class'=>'col-md-3 control-label']) !!}
  <div class="col-md-9">
      {!! Form::number('paid_total', $transaction->confirmation->paid_total, ['class'=>'form-control']) !!}
      {!! $errors->first('paid_total', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Bukti Transfer', ['class'=>'col-md-3 control-label']) !!}
  <div class="col-md-9">
    @if (isset($transaction->confirmation) && $transaction->confirmation->image)
     <p> {!! Html::image(asset('img/'.$transaction->confirmation->image), null, ['class'=>'img-rounded img-responsive']) !!} </p>
    @else
      {!! Form::text('null', 'User belum mengunggah bukti transfer', ['class'=>'form-control','readonly']) !!}
    @endif
    {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-9 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/transactions/_form.blade.php
<div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
  <label class="col-md-2 control-label">Kode Transaksi</label>
  <div class="col-md-4">
    <input type="text" class="form-control" value="{{$transaction->code}}" readonly>
    {!! $errors->first('code', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('user_id') ? 'has-error' : '' !!}">
  {!! Form::label('user_id', 'Nama Pelanggan', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('user_id', [''=>'']+App\User::pluck('name','id')->all(), null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Pelanggan']) !!}
    {!! $errors->first('user_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('place_id') ? 'has-error' : '' !!}">
  {!! Form::label('place_id', 'Tempat Tujuan', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('place_id', [''=>'']+App\Place::pluck('name','id')->all(), null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Ttempat Tujuan']) !!}
    {!! $errors->first('place_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('car_id') ? 'has-error' : '' !!}">
  {!! Form::label('car_id', 'Merk Mobil', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('car_id', [''=>'']+App\Car::pluck('name','id')->all(), null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Merk Mobil']) !!}
    {!! $errors->first('car_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('total_participants') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Jumlah Orang', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::number('total_participants', null, ['class'=>'form-control']) !!}
    {!! $errors->first('total_participants', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Tanggal Pergi', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::date('start_date', null, ['class'=>'form-control']) !!}
    {!! $errors->first('start_date', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Tanggal Kembali', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::date('end_date', null, ['class'=>'form-control']) !!}
    {!! $errors->first('end_date', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('total_cost') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Harga', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::number('total_cost', null, ['class'=>'form-control']) !!}
    {!! $errors->first('total_cost', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('status') ? 'has-error' : '' !!}">
  {!! Form::label('name', 'Status', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('status',[
      'pending'=>'Pending',
      'confirmed'=>'Confirmed',
      'completed' => 'Completed',
      'canceled' => 'Canceled'
    ],null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Status']) !!}
    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/transactions/confirmation.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
      		<li><a href="{{ url('/admin/transactions') }}">Transaction</a></li>
      		<li class="active">Confirmation</li>
        </ul>
        <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h2 class="panel-title">Data Transaksi</h2>
              </div>
              <div class="panel-body">
                <form class="form-horizontal">
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Pelanggan</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->user->name}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Tempat Tujuan</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->place->name}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Mobil</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->car->name}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Jumlah Orang</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->total_participants}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Tanggal Pergi</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->start_date}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Tanggal Kembali</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->end_date}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Total Harga</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->total_cost}}" readonly>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Status</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" value="{{$transaction->status}}" readonly>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="panel-title">Confirmation</h2>
            </div>
            <div class="panel-body">
              {!! Form::model($confirmation, ['url' => route('confirmations.update', $transaction->confirmation->id),'method'=>'put', 'class'=>'form-horizontal']) !!}
              @include('transactions._conf')
              {!! Form::close() !!}
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
@endsection

resources/views/transactions/edit.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
      		<li><a href="{{ url('/admin/transactions') }}">Transaction</a></li>
      		<li class="active">Edit Transaction</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Edit Transaction</h2>
          </div>
          <div class="panel-body">
            {!! Form::model($transaction, ['url' => route('transactions.update', $transaction->id),'method'=>'put', 'class'=>'form-horizontal']) !!}
            @include('transactions._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/transactions/export.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
  @include('layouts._flash')
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ route('transactions.index') }}">Transactions</a></li>
          <li class="active">Transactions Report</li>
        </ul>
        <div class="box">
          <div class="box-header with-border">
            <h2 class="box-title">Transactions Report</h2>
          </div>
          <div class="box-body">

            {!! Form::open(['url' => route('export.transactions.post'),'method' => 'post', 'class'=>'form-horizontal']) !!}
            <div class="form-group {!! $errors->has('month') ? 'has-error' : '' !!}">
              {!! Form::label('name', 'Berdasarkan bulan', ['class'=>'col-md-2 control-label']) !!}
                <div class="col-md-4">
                  {!! Form::select('month',[
                    '1'=>'Januari',
                    '2'=>'Februari',
                    '3'=>'Maret',
                    '4'=>'April',
                    '5'=>'Mei',
                    '6'=>'Juni',
                    '7'=>'Juli',
                    '8'=>'Agustus',
                    '9'=>'September',
                    '10'=>'Oktober',
                    '11'=>'November',
                    '12'=>'Desember'
                  ],null,[
                    'class'=>'form-control',
                    'placeholder' => 'Pilih Bulan']) !!}
                  {!! $errors->first('month', '<p class="help-block">:message</p>') !!}
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-4 col-md-offset-2">
                  {!! Form::submit('Download', ['class'=>'btn btn-primary']) !!}
                </div>
              </div>
              {!! Form::close() !!}

          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/transactions/index.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
  @include('layouts._flash')
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Transaction</li>
        </ul>
        <div class="box">
          <div class="box-header with-border">
            <h2 class="box-title">Transaction</h2>
          </div>
          <div class="box-body">
            <p>
              <a class="btn btn-primary" href="{{ url('/admin/export/transactions') }}"><i class="fa fa-download"></i>
                Export Transactions Report</a>
            </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('js')
{!! $html->scripts() !!}
@endsection