routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//route landing page
Route::get('/', 'LandingPageController@welcome');
Route::get('place/view/{id}', 'LandingPageController@placeview');
Route::get('/about', function () {
    return view('about');
});

//route verifikasi user
Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//route front search
Route::get('search-destination', ['as'=>'search-destination','uses'=>'AllSearchController@destination']);
Route::get('search-budget', ['as'=>'search-budget','uses'=>'AllSearchController@budget']);
Route::get('search-car', ['as'=>'search-car','uses'=>'AllSearchController@car']);

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
  Route::resource('cartypes', 'CarTypesController');
  Route::resource('cars', 'CarsController');
  Route::resource('categories', 'CategoriesController');
  Route::resource('places', 'PlacesController');
  Route::resource('transactions', 'TransactionsController');
  Route::resource('confirmations', 'ConfirmationsController');
  Route::resource('members', 'MembersDataController');
  /*
   * route myprofil dan ubah *admin*
   */
  Route::get('settings', 'SettingsController@profile');
  Route::post('settings', 'SettingsController@update');
  Route::get('settings/password', 'SettingsController@editPassword');
  Route::post('settings/password', 'SettingsController@updatePassword');
  /*
   *  export laporan
   */
  Route::get('export/transactions', [
    'as' => 'export.transactions',
    'uses' => 'TransactionsController@export'
  ]);
  Route::post('export/transactions', [
    'as' => 'export.transactions.post',
    'uses' => 'TransactionsController@exportPost'
  ]);

});

Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function () {
  Route::resource('orders', 'MemberOrdersController');
  Route::get('orders/confirmation/{id}', 'MemberOrdersController@conf');
  Route::post('orders/confirmation/{id}', 'MemberOrdersController@storeconf');
  Route::get('orders/dest/{id}', 'MemberOrdersController@orderdest');
  Route::get('orders/car/{id}', 'MemberOrdersController@ordercar');
  Route::get('orders/cetak/{id}', 'MemberOrdersController@cetak');
  /*
  --route myprofil dan ubah password *member*
  */
  Route::get('settings', 'MemberSettingsController@profile');
  Route::post('settings', 'MemberSettingsController@update');
  Route::get('settings/password', 'MemberSettingsController@editPassword');
  Route::post('settings/password', 'MemberSettingsController@updatePassword');
});


/*
-- route ajax dropdown wilayah
*/
Route::get('/admin/places/kabupaten/{id}', 'PlacesController@kabupaten');
Route::get('/admin/places/kecamatan/{id}', 'PlacesController@kecamatan');
Route::get('/admin/places/kelurahan/{id}', 'PlacesController@kelurahan');

app/Http/Controllers/MembersDataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\User;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Facades\Datatables;
use App\Http\Requests\StoreMemberRequest;
use App\Http\Requests\UpdateMemberRequest;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Mail;

class MembersDataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index(Request $request, Builder $htmlBuilder)
     {
         if ($request->ajax()) {
           $members = Role::where('name', 'member')->first()->users;
           return Datatables::of($members)
           ->addColumn('action', function($member){
             return view('datatable._action', [
               'model' => $member,
               'form_url' => route('members.destroy', $member->id),
               'edit_url' => route('members.edit', $member->id),
               'confirm_message' => 'Yakin mau menghapus ' . $member->name . '?'
             ]);
           })->make(true);
         }

         $html = $htmlBuilder
         ->addColumn(['data' => 'name', 'name'=>'name', 'title'=>'Nama'])
         ->addColumn(['data' => 'username', 'name'=>'username', 'title'=>'Username'])
         ->addColumn(['data' => 'email', 'name'=>'email', 'title'=>'Email'])
         ->addColumn(['data' => 'mobile_phone', 'name'=>'mobile_phone', 'title'=>'Telepon'])
         ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

         return view('membersdata.index', compact('html'));
     }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('membersdata.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(StoreMemberRequest $request)
     {
       $password = str_random(6);
       $data = $request->all();
       $data['password'] = bcrypt($password);
       // bypass verifikasi
       $data['is_verified'] = 1;

       $member = User::create($data);

       // set role
       $memberRole = Role::where('name', 'member')->first();
       $member->attachRole($memberRole);

       // kirim email
       Mail::send('auth.emails.invite', compact('member', 'password'), function ($m) use ($member) {
         $m->to($member->email, $member->name)->subject('Anda telah didaftarkan di BandungTranService!');
       });

       Session::flash("flash_notification", [
         "level" => "success",
         "message" => "Berhasil menyimpan member dengan email " .
         "<strong>" . $data['email'] . "</strong>" .
         " dan password <strong>" . $password . "</strong>."
       ]);
       return redirect()->route('members.index');
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $member = User::find($id);
      return view('membersdata.edit')->with(compact('member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function update(UpdateMemberRequest $request, $id)
     {
       $member = User::find($id);
       $member->update($request->only('name','username','email','mobile_phone'));

       Session::flash("flash_notification", [
         "level"=>"success",
         "message"=>"Berhasil mengubah $member->name"
       ]);

       return redirect()->route('members.index');
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $member = User::find($id);
      if ($member->hasRole('member')) {
        $member->delete();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Member berhasil dihapus"
        ]);

      }
      return redirect()->route('members.index');
    }
}

resources/views/membersdata/_form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Nama', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Username', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('username', null, ['class'=>'form-control']) !!}
    {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
  {!! Form::label('email', 'Email', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::email('email', null, ['class'=>'form-control']) !!}
    {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('mobile_phone') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Telepon', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::number('mobile_phone', null, ['class'=>'form-control']) !!}
    {!! $errors->first('mobile_phone', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/membersdata/create.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
  @include('layouts._flash')
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Add Member</li>
        </ul>
        <div class="box">
          <div class="box-header with-border">
            <h2 class="box-title">Add Member</h2>
          </div>
          <div class="box-body">
            {!! Form::open(['url' => route('members.store'),'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
              @include('membersdata._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/membersdata/edit.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
      		<li><a href="{{ url('/admin/members') }}">Member</a></li>
      		<li class="active">Edit Member</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Edit Member</h2>
          </div>
          <div class="panel-body">
            {!! Form::model($member, ['url' => route('members.update', $member->id),'method'=>'put', 'class'=>'form-horizontal']) !!}
            @include('membersdata._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/membersdata/index.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
  @include('layouts._flash')
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Members</li>
        </ul>
        <div class="box">
          <div class="box-header with-border">
            <h2 class="box-title">Members</h2>
          </div>
          <div class="box-body">
            <p> <a class="btn btn-primary" href="{{ url('/admin/members/create') }}">Tambah</a> </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('js')
{!! $html->scripts() !!}
@endsection