routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//route landing page
Route::get('/', 'LandingPageController@welcome');
Route::get('place/view/{id}', 'LandingPageController@placeview');
Route::get('/about', function () {
    return view('about');
});

//route verifikasi user
Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//route front search
Route::get('search-destination', ['as'=>'search-destination','uses'=>'AllSearchController@destination']);
Route::get('search-budget', ['as'=>'search-budget','uses'=>'AllSearchController@budget']);
Route::get('search-car', ['as'=>'search-car','uses'=>'AllSearchController@car']);

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
  Route::resource('cartypes', 'CarTypesController');
  Route::resource('cars', 'CarsController');
  Route::resource('categories', 'CategoriesController');
  Route::resource('places', 'PlacesController');
  Route::resource('transactions', 'TransactionsController');
  Route::resource('confirmations', 'ConfirmationsController');
  Route::resource('members', 'MembersDataController');
  /*
   * route myprofil dan ubah *admin*
   */
  Route::get('settings', 'SettingsController@profile');
  Route::post('settings', 'SettingsController@update');
  Route::get('settings/password', 'SettingsController@editPassword');
  Route::post('settings/password', 'SettingsController@updatePassword');
  /*
   *  export laporan
   */
  Route::get('export/transactions', [
    'as' => 'export.transactions',
    'uses' => 'TransactionsController@export'
  ]);
  Route::post('export/transactions', [
    'as' => 'export.transactions.post',
    'uses' => 'TransactionsController@exportPost'
  ]);

});

Route::group(['prefix'=>'member', 'middleware'=>['auth', 'role:member']], function () {
  Route::resource('orders', 'MemberOrdersController');
  Route::get('orders/confirmation/{id}', 'MemberOrdersController@conf');
  Route::post('orders/confirmation/{id}', 'MemberOrdersController@storeconf');
  Route::get('orders/dest/{id}', 'MemberOrdersController@orderdest');
  Route::get('orders/car/{id}', 'MemberOrdersController@ordercar');
  Route::get('orders/cetak/{id}', 'MemberOrdersController@cetak');
  /*
  --route myprofil dan ubah password *member*
  */
  Route::get('settings', 'MemberSettingsController@profile');
  Route::post('settings', 'MemberSettingsController@update');
  Route::get('settings/password', 'MemberSettingsController@editPassword');
  Route::post('settings/password', 'MemberSettingsController@updatePassword');
});


/*
-- route ajax dropdown wilayah
*/
Route::get('/admin/places/kabupaten/{id}', 'PlacesController@kabupaten');
Route::get('/admin/places/kecamatan/{id}', 'PlacesController@kecamatan');
Route::get('/admin/places/kelurahan/{id}', 'PlacesController@kelurahan');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Car extends Model
{
  use Searchable;

  //mass assignment
  protected $fillable = ['name','car_type_id','sheet','cost','status'];

  public function searchableAs()
  {
     return 'cars_index';
  }

  public function car_type()
    {
      return $this->belongsTo('App\Car_type');
    }

  public function transaction()
    {
        return $this->hasOne('App\Transaction');
    }
}

app/Car_type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car_type extends Model
{
    protected $fillable = ['name'];

    public function car()
      {
        return $this->hasMany('App\Car');
      }
}

app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Car;
use Yajra\Datatables\Datatables;
use Yajra\Datatables\Html\Builder;

class CarsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index(Request $request, Builder $htmlBuilder)
       {
         if ($request->ajax()) {
           $cars = Car::with('car_type');
           return Datatables::of($cars)
             ->addColumn('action', function($car){
               return view('datatable._action', [
                 'model' => $car,
                 'form_url' => route('cars.destroy', $car->id),
                 'edit_url' => route('cars.edit', $car->id),
                 'confirm_message' => 'Yakin mau menghapus ' . $car->name . '?'
               ]);
             })->make(true);
           }

           $html = $htmlBuilder
             ->addColumn(['data' => 'name', 'name'=>'name', 'title'=>'Merk Mobil'])
             ->addColumn(['data' => 'car_type.name', 'name'=>'car_type.name', 'title'=>'Tipe Mobil'])
             ->addColumn(['data' => 'sheet', 'name'=>'sheet', 'title'=>'Jumlah Kursi'])
             ->addColumn(['data' => 'cost', 'name'=>'cost', 'title'=>'Harga'])
             ->addColumn(['data' => 'status', 'name'=>'status', 'title'=>'Status'])
             ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

             return view('cars.index')->with(compact('html'));
       }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('cars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required',
          'car_type_id' => 'required',
          'sheet' => 'required',
          'cost' => 'required',
          'status' => 'required'
        ]);
        $car = Car::create($request->all());

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Berhasil menyimpan $car->name"
        ]);

        return redirect()->route('cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $car = Car::find($id);
      return view('cars.edit')->with(compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
        'name' => 'required',
        'car_type_id' => 'required',
        'sheet' => 'required',
        'cost' => 'required',
        'status' => 'required'
      ]);

      $car = Car::find($id);
      $car->update($request->all());

      Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Berhasil mengubah $car->name"
      ]);

    return redirect()->route('cars.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Car::destroy($id);

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Data Berhasil dihapus"
        ]);

        return redirect()->route('cars.index');
    }
}

resources/views/cars/_form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Merk Mobil', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('car_type_id') ? 'has-error' : '' !!}">
  {!! Form::label('car_type_id', 'Tipe Mobil', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('car_type_id', [''=>'']+App\Car_type::pluck('name','id')->all(), null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Tipe Mobil']) !!}
    {!! $errors->first('car_type_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('sheet') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Jumlah Kursi', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::number('sheet', null, ['class'=>'form-control']) !!}
    {!! $errors->first('sheet', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('cost') ? ' has-error' : '' }}">
  {!! Form::label('name', 'Harga', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('cost', null, ['class'=>'form-control']) !!}
    {!! $errors->first('cost', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('status') ? 'has-error' : '' !!}">
  {!! Form::label('name', 'Status', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('status',['available'=>'Available', 'booked'=>'Booked'],null,[
      'class'=>'form-control',
      'placeholder' => 'Pilih Status']) !!}
    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/cars/create.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/admin/cars') }}">Car</a></li>
          <li class="active">Add Car</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Add Car</h2>
          </div>
          <div class="panel-body">
            {!! Form::open(['url' => route('cars.store'),'method' => 'post', 'class'=>'form-horizontal']) !!}
            @include('cars._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/cars/edit.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
      		<li><a href="{{ url('/admin/cars') }}">Car</a></li>
      		<li class="active">Edit Car</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Edit Car</h2>
          </div>
          <div class="panel-body">
            {!! Form::model($car, ['url' => route('cars.update', $car->id),'method'=>'put', 'class'=>'form-horizontal']) !!}
            @include('cars._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/cars/index.blade.php
@extends('adminlte::page')

@section('content')
  <div class="container-fluid spark-screen">
  @include('layouts._flash')
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Car</li>
        </ul>
        <div class="box">
          <div class="box-header with-border">
            <h2 class="box-title">Car</h2>
          </div>
          <div class="box-body">
            <p> <a class="btn btn-primary" href="{{ route('cars.create') }}">Tambah</a> </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('js')
{!! $html->scripts() !!}
@endsection